### ISSUE TITLE
Multi-Dimensional Arrays

### ISSUE THREAD

**Issue by dwwork** [marshallward/f90nml#14]
I'm interested in using f90nml for my work, but just need the multi-dimensional array support. I'm willing to do the work for it, but was wondering what your thoughts are on how to put the support in. I found the TODO on line 182 of parser.py, so I assume most of it will need to go in there somewhere.
Thanks.

**Comment by marshallward** [comment]
Thanks, that would be great if you can find the time to implement it.

In many cases, it isn't necessary to specify the dimensions, since an entry like this

    x = 1, 2, 3, 4

could be used to populate both a 2x2 and 4x1 array. But it would be difficult to work with inside Python.

I believe that the index parsing (`parse_index`) will correctly parse multiple dimensions. But the `v_idx` iterator assumes a single dimension. So v_idx would have to be modifed to return a tuple, rather than a single index, and that would require more changes throughout.

Also, its not clear to me how to best implement the multidimensional arrays. Numpy `ndarray` is the most natural, but I would prefer to not make numpy a requirement. List of lists is probably the safest bet. It would probably be best to support both, with `use_numpy` flag to support `ndarray`s.

Anyway, those are my thoughts, but feel free to have a crack at it, and see how you go.

**Comment by dwwork** [comment]
So, this is harder than I thought! I came up with the idea of making a multi-dimensional class to wrap a list of lists. The idea is that it would act like a linear list or a non-linear array, depending. 
I had to change the index parser a bit, it didn't read the multiple dimensions correctly. I think that part is working fine. AFAIK, the multiD class is working as well. I just don't know how to get it to work with everything else. I've pushed a branch to my fork, here:

https://github.com/dwwork/f90nml/tree/multiD

What do you think?


https://github.com/dwwork/f90nml/tree/multiD

**Comment by marshallward** [comment]
Thanks for this!
I'm currently on vacation but I'll have a look over get back in about two weeks.

**Comment by marshallward** [comment]
Sorry for the long silence on this.  I've started working on this beginning
with your branch.

I think the only problem with your solution was a misplaced
update_tokens(). Moving that inside the index parsing seemed to have solved
it.

I haven't yet incorporated your multid stuff, and ended up writing a new
index iterator (probably the only difference is that it's more 3.x
compatible).

This is the branch:

https://github.com/marshallward/f90nml/tree/md

Current version does not yet support multidim arrays but multidim indexing
works (then subsequently ignored), and all the test cases work.

I think your list-of-list idea is the correct one, and will also work
towards that solution.

**Comment by dwwork** [comment]
Thanks for taking a look at this. I just under went a wrist surgery and I can't type. It will probably be another 6-8 weeks before I can work on this again. I will take a look at the branch that you linked.

**Comment by marshallward** [comment]
There is now an implementation that converts multidimensional arrays to list of lists.  I'm still testing through the cases but so far so good.

`write` still fails to interpret these and causes a crash when you try to output the namelist.

**Comment by marshallward** [comment]
This is all working now (in principle at least) so I'm closing this issue.

Any specific problems can be resolved in separate issues.

**Comment by dwwork** [comment]
Thanks! I've been swamped with life and haven't been able to look at it yet. I'll see if it works when I have some free time.
